### ISSUE TITLE
Explore onecloud for GPU CI

### ISSUE THREAD

**Issue by kurapov-peter** [intel/graph-compiler#140]

**Comment by leshikus** [comment]
I've discussed with Vadim a common approach for using the cloud machines. The idea is to build a runner image which we can redeploy after the machine lease is completed.

Will try to make a prototype after Vadim figures out how to update the kernel in the image

**Comment by lmontigny** [comment]
need at lest 3x GPU for CI (may need more later)

**Comment by leshikus** [comment]
There were no update from onecloud owners during this week

**Comment by lmontigny** [comment]
no update 09/10, found alternative solution internally
