### ISSUE TITLE
Add GPU runner

### ISSUE THREAD

**Issue by kurapov-peter** [intel/graph-compiler#144]

**Comment by kurapov-peter** [comment]
> I need something to test GPU runner on

You can run gpu tests from here: https://github.com/intel/graph-compiler/tree/main/test/mlir/test/gc/gpu-runner. They are included into the gc-check target when `gc_use_imex` is true.

**Comment by leshikus** [comment]
Verified https://github.com/intel/graph-compiler/actions/runs/10389153003/job/28767124005
