### ISSUE TITLE
LLVM Build does not support MLIR python binding now

### ISSUE THREAD

**Issue by WangJialei-A** [intel/graph-compiler#163]
\+ @ZhennanQin 

We need to enable `-DMLIR_ENABLE_BINDINGS_PYTHON=ON` at `cmake` step to proceed our development work.

Some related component may also need to be installed in the container image?
1. numpy?
2. python3-dev?

**Comment by leshikus** [comment]
Should I use `pip` to install `numpy`?

**Comment by leshikus** [comment]
dev env uses conda; which conda package should I use for `python3-dev`?

**Comment by leshikus** [comment]
I have updated the runner, please let me know if it is the change you need

```
diff --git a/.github/dockerfiles/runner/Dockerfile b/.github/dockerfiles/runner/Dockerfile
index 0909c26..be499d3 100644
--- a/.github/dockerfiles/runner/Dockerfile
+++ b/.github/dockerfiles/runner/Dockerfile
@@ -10,13 +10,13 @@ RUN set -ex; \
     curl -sSL https://cli.github.com/packages/githubcli-archive-keyring.gpg > /usr/share/keyrings/githubcli-archive-keyring.gpg; \
     apt-get update -y; \
     apt-get install -y --no-install-recommends --fix-missing \
-      python3-pip \
+      python3-pip python3-dev \
       cmake gcc g++ ninja-build git clang-format \
       gh \
     ; \
     rm -rf /var/lib/apt/lists/*

-RUN pip install lit
+RUN pip install lit numpy

 USER runner
 WORKDIR $HOME
```

**Comment by WangJialei-A** [comment]
Not work for me now...
Please have a look at the error message in this run. Is it possible for me to access these runner directly?
https://github.com/intel/graph-compiler/actions/runs/9900257824/job/27350701517

**Comment by WangJialei-A** [comment]
@leshikus 
I rebuild the docker image locally and reproduce the problem.
The problem is the container image `summerwind:actions-runner` is not compatible with numpy. 
numpy will raise error `ImportError: /home/runner/.local/lib/python3.10/site-packages/numpy/_core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so: rebuild shared object with SHSTK support enabled` after import numpy

**Comment by WangJialei-A** [comment]
@leshikus 
Did you update the runner correctly?
I track the syscall of cmake with strace. It seems that python3-dev is not installed.
https://github.com/intel/graph-compiler/actions/runs/9904464495/job/27361928937

![image](https://github.com/user-attachments/assets/2a7bcf1a-8d09-465a-b02c-62c7fd2016fa)

**Comment by leshikus** [comment]
I have checked with `dpkg`, there is no `python3-dev`, will try to fix this

**Comment by leshikus** [comment]
runner seem to work now https://github.com/intel/graph-compiler/actions/runs/9909347808/job/27377200703
