### ISSUE TITLE
[GPU] Remove dependency on tpp's `StructuredOpMatcher` from LinalgToXeGPU conversion

### ISSUE THREAD

**Issue by dchigarev** [intel/graph-compiler#166]
We want to get rid of this file essentially:
https://github.com/intel/graph-compiler/blob/main/lib/gc/Transforms/Utils/StructuredOpMatcher.cpp

**Comment by huanghaixin008** [comment]
Hi dmitry, I have exactly the same dependency in this PR for CPU microkernel pipeline: [#114](https://github.com/intel/graph-compiler/pull/114), maybe we can share some joint effort to remove the dependency.

**Comment by dchigarev** [comment]
> Hi dmitry, I have exactly the same dependency in this PR for CPU microkernel pipeline: [#114](https://github.com/intel/graph-compiler/pull/114), maybe we can share some joint effort to remove the dependency.

@huanghaixin008 have you made any progress so far in removing this dependency? I'm wondering, whether we should remove this (if it's not trivial) since there are already several places in GC where we depend on it 
cc @kurapov-peter

**Comment by dchigarev** [comment]
@huanghaixin008 

Initially when I was copying LinalgToXeGPU pass from tpp-mlir, I wanted to bring to GC as less external utils as possible. `StructuredOpMatcher` seemed as a redundant and easy-removable thing at first. Now given the facts, that it appeared not so trivial to remove, and that other parts of GC start also depending on these utils, it seems more logical to leave them in our project with no changes.

So no changes to `StructuredOpMatcher` and other utils, that I've added in #165, are planned from my side. Thus closing the issue.
