### ISSUE TITLE
OV GPU integration

### ISSUE THREAD

**Issue by kurapov-peter** [intel/graph-compiler#207]

**Comment by dchigarev** [comment]
Openvino branch with the current state: https://github.com/dchigarev/openvino/tree/gc-gpu (semi-working)

<b>Current status:</b>
There are two pipelines in OpenVINO that can use our GC-GPU pipeline:
1. OpenVINO CPU:
    - the data is originally on CPU
    - the mlir module accepts CPU pointers
    - our module copies the data to GPU and the result back to CPU

    The integration GC-GPU with the openVINO CPU works. A simple mlir module can be executed and the output result is correct.

2. OpenVINO GPU (star* marked points mean, that they're not yet implemented):
    - the data is originally on GPU (cl::Buffer)
    - *the mlir module accepts pointers to (cl_mem/cl::Buffer)
    - *the mlir module accepts a pointer to cl::CommandQueue (that contains information about device)
    - *the mlir module using [our OpenCLRuntimeWrapper](https://github.com/intel/graph-compiler/blob/main/lib/gc/ExecutionEngine/OpenCLRuntime/OpenCLRuntimeWrappers.cpp) submits our kernel to the received queue
   
    This part doesn't function for now. Working on it.

<details><summary>An example of a simple MLIR module that GC receives from openVINO</summary>

```mlir
module @fragment_name {
  func.func @entry(%arg0: memref<64x128xf32>, %arg1: memref<128x128xf32>, %arg2: memref<64x128xf32>) {
    %0 = bufferization.to_tensor %arg0 restrict : memref<64x128xf32>
    %1 = bufferization.to_tensor %arg1 restrict : memref<128x128xf32>
    %2 = tensor.empty() : tensor<64x128xf32>
    %cst = arith.constant 0.000000e+00 : f32
    %3 = linalg.fill ins(%cst : f32) outs(%2 : tensor<64x128xf32>) -> tensor<64x128xf32>
    %4 = linalg.matmul ins(%0, %1 : tensor<64x128xf32>, tensor<128x128xf32>) outs(%3 : tensor<64x128xf32>) -> tensor<64x128xf32>
    %5 = tensor.empty() : tensor<64x128xf32>
    %6 = linalg.add ins(%4, %0 : tensor<64x128xf32>, tensor<64x128xf32>) outs(%5 : tensor<64x128xf32>) -> tensor<64x128xf32>
    bufferization.materialize_in_destination %6 in restrict writable %arg2 : (tensor<64x128xf32>, memref<64x128xf32>) -> ()
    return
  }
}
```

</details>

**Comment by kurapov-peter** [comment]
I think we can skip the queue passing (#230) for the time being and create a new one each time we submit a kernel. This should still be functional, queue passing should be a separate problem.

**Comment by dchigarev** [comment]
<b>Current status:</b>
1. Simple openvino subgraphs are successfully compiled executed using GPU pipeline from GC
2. GPU buffers allocated on OpenVino side are successfully propagated and obtained by our openclRuntime (*with hacks that help to distinguish between USM and cl::Buffer in openclRuntime. See 'Things left to do.1' for more info)
3. Working on a set of sanity-tests in OpenVino for this.

<b>Things left to do:</b>
1. We need to distinguish between USM and cl::Buffer pointers in our [OpenCLRuntimeWrapper::launchKernel](https://github.com/intel/graph-compiler/blob/bc7f33b0d89b6d9a944c39c8adef88047f291a78/lib/gc/ExecutionEngine/OpenCLRuntime/OpenCLRuntimeWrappers.cpp#L321) as we need to handle them differently when [setting as a kernel's argument](https://github.com/intel/graph-compiler/blob/bc7f33b0d89b6d9a944c39c8adef88047f291a78/lib/gc/ExecutionEngine/OpenCLRuntime/OpenCLRuntimeWrappers.cpp#L338-L344) (we have to call `clSetKernelArg` for cl::Buffer and `clSetKernelArgMemPointerINTEL` for USM). 

    There are two possibilities:
    - a. Use `clGetMemAllocInfoINTEL` to determine if a pointer we're dealing with is a USM (requires openvino's cl::queue and context)
    - b. Figure out a structure that describes which argument is what and pass it from openvino to our runtime
   
    For now we're waiting for #230 to be completed and then we'll try to go with the option 'a.'

4. Figure out a mechanism of how we can pass openvino's cl::queue to our openclRuntime (#230). The queue can be extracted from [here](https://github.com/slyalin/openvino/blob/4e32925dcb2b9ac0a222788df5da6d715093d502/src/plugins/intel_gpu/src/plugin/ops/mlir_op.cpp#L29) as `dynamic_cast<cldnn::ocl::ocl_stream&>(stream).get_cl_queue()` and then propagated to the MLIR module
5. Support more linalg operations in `linalg-to-xegpu` pass. OpenVino tends to produce `linalg.matmul_transpose_*` operations that are not supported by our xegpu lowering. The unsupported operations still work though but xegpu ops are not used.

    For example: in case `linalg.matmul_transpose_b` regular `arith.mulf + arith.addf` in a for loops would be used instead of `xegpu.dpas` intrinsic.


<details><summary>An example of a simple MLIR module that GC receives from openVINO</summary>

```mlir
module @fragment_name {
  func.func @entry(%arg0: memref<64x128xf32>, %arg1: memref<128x128xf32>, %arg2: memref<64x128xf32>) {
    %0 = bufferization.to_tensor %arg0 restrict : memref<64x128xf32>
    %1 = bufferization.to_tensor %arg1 restrict : memref<128x128xf32>
    %2 = tensor.empty() : tensor<64x128xf32>
    %cst = arith.constant 0.000000e+00 : f32
    %3 = linalg.fill ins(%cst : f32) outs(%2 : tensor<64x128xf32>) -> tensor<64x128xf32>
    %4 = linalg.matmul ins(%0, %1 : tensor<64x128xf32>, tensor<128x128xf32>) outs(%3 : tensor<64x128xf32>) -> tensor<64x128xf32>
    %5 = tensor.empty() : tensor<64x128xf32>
    %6 = linalg.add ins(%4, %0 : tensor<64x128xf32>, tensor<64x128xf32>) outs(%5 : tensor<64x128xf32>) -> tensor<64x128xf32>
    bufferization.materialize_in_destination %6 in restrict writable %arg2 : (tensor<64x128xf32>, memref<64x128xf32>) -> ()
    return
  }
}
```

cc @AndreyPavlenko

**Comment by AndreyPavlenko** [comment]
A few additions.

 - The clGetMemAllocInfoINTEL approach seems not reliable. A better solution could be adding the memory address space attribute to the inputs, but some pathses do not handle it properly and/or fail. I've fixed some known issues and now this approach works for my test scenarios.
 - The GPU pipeline does not work when it's merged with the main branch. Seems the root cause is https://github.com/intel/graph-compiler/pull/280 . The imex llvm version should be updated to https://github.com/llvm/llvm-project/commit/f06563a5c0d239a6b98f74db522681613254ad08 , but imex build fails with this version due to incompatible patches. I've fixed the patches, but the build is still failing. Working on it.

**Comment by dchigarev** [comment]
PR to OV with the integration: https://github.com/slyalin/openvino/pull/169

**Comment by dchigarev** [comment]
<b> Current status: </b>

1. Have made a PR to OV with the first version of integration slyalin/openvino#169. The PR also includes a simple sanity tests for the integration.
2. @AndreyPavlenko is working on propagating OpenCL queue and other meta-info from OV to GC (#230). The first draft version is already present in the integration PR in OV.
3. Submitted first PRs to GC and IMEX that port the changes required for the integration from our forks to upstream:
    - intel/graph-compiler#329
    - intel/mlir-extensions#866
    - intel/mlir-extensions#857
    - intel/mlir-extensions#856
    - intel/mlir-extensions#851
    - there could be more on the way... (check the following section)

<b> Things left to do: </b>

1. Decide on how to propagate the information to `insert-gpu-allocs` pass that the input memrefs are already on GPU:
    1. <b>Approach A - the proper one: </b> Assign `#gpu.address_space` to the input memrefs on the OV side and add a logic to the `insert-gpu-allocs` pass that acknowledges them. 
    
        The problem with this approach is that certain passes of the GPU pipeline fail if `#gpu.address_space` attribute is assigned to memrefs. A proper solution for that is to [patch `MemrefToSpirv` pass from LLVM](https://github.com/AndreyPavlenko/mlir-extensions/commit/346e9078f1563acc88925159a9f9b6b3f59715c4), a hacky solution is to forcibly remove `#gpu.address_space` attribute from all memrefs right after `insert-gpu-allocs` pass.
    2. <b>Approach B - hacky but simple: </b> simply add a parameter to the `insert-gpu-allocs` pass that would indicate that all input memrefs are on GPU and it shouldn't do anything about them.
    
    We're leaning to the <b>Approach A</b> for now. Although it looks more difficult, all the parts of the approach are already implemented:
    - Assigning `#gpu.address_space` could be done using [`gc::AddRemoveGpuAddressSpace` pass](https://github.com/AndreyPavlenko/graph-compiler/blob/131e5a811c63c1a27590b4503c5c61c43c274239/lib/gc/Transforms/GPU/AddRemoveGpuAddressSpace.cpp#L23) from Andrey's fork of GC. The pass is expected to be [applied at the beginning of the GC pipeline in OV](https://github.com/AndreyPavlenko/openvino/blob/2a902cb997e87e821a13d6238cf016f4483c93bf/src/common/transformations/src/transformations/mlir/mlir_op.cpp#L89-L90).
    - Acknowledging the address spaces by the `insert-gpu-allocs` pass is also [already implemented](https://github.com/AndreyPavlenko/mlir-extensions/commit/bb8111fe89867de5d24c32f2bf52744be04b2cae) by Andrey in his fork of IMEX.
    - Patch to LLVM that fixes failures in our pipeline caused by `#gpu.address_space` is also [implemented](https://github.com/AndreyPavlenko/mlir-extensions/commit/346e9078f1563acc88925159a9f9b6b3f59715c4)
    - If we'll decide not to patch LLVM, a pass to remove `#gpu.address_space`s is also [already implemented](https://github.com/AndreyPavlenko/graph-compiler/blob/131e5a811c63c1a27590b4503c5c61c43c274239/lib/gc/Transforms/GPU/AddRemoveGpuAddressSpace.cpp#L23)

    If we are choosing <b>Approach A</b> we only need to decide on how we're going to fix the GPU pipeline failure caused by `#gpu.address_spaces`. Should this be a patch to LLVM or are we okay to simply remove the addr spaces once we've done with them? @AndreyPavlenko @kurapov-peter thoughts?

2. Decide on what we consider a "completed integration". @kurapov-peter do we want to have something specific to work via our OpenVino -> GC pipeline (some models or something, how complex they should be)? Do we want to establish some benchmarks in OV?
3. The GPU buffers on the OV side are often allocated as USM Host memory, this may potentially harm performance. Need to figure out why it's happening and what's the real impact.

**Comment by dchigarev** [comment]
PRs in GC that are left to merge to make the integration working:
1. #343
2. #333
3. #347 
4. #344 ([Add/Remove gpu address spaces](https://github.com/AndreyPavlenko/graph-compiler/blob/131e5a811c63c1a27590b4503c5c61c43c274239/lib/gc/Transforms/GPU/AddRemoveGpuAddressSpace.cpp#L23))

**Comment by kurapov-peter** [comment]
Closing as completed
