### ISSUE TITLE
Define linalg ternary operation type and add select op

### ISSUE THREAD

**Issue by rengolin** [intel/graph-compiler#23]
To be able to add a `select` named operation in linalg we'll need to define a ternary operation type on the OpDSL mechanism and add the op with the appropriate semantics.

Here's a branch with some of that work done, just need to work through the OpDSL framework and make it work.
https://github.com/rengolin/llvm-project/tree/linalg-ternary-select

Current semantics is: `linalg.select ins(%cond, %lhs, %rhs) outs(%out) : tensor<...xbool>, tensor<...xTy>,  tensor<...xTy>,  tensor<...xTy>`

**Comment by kurapov-peter** [comment]
Update: This currently misses some scalar enum value for ternary in the ODS which I'm trying to track down. So far I've hit the same issue described here https://github.com/llvm/llvm-project/issues/67414 when generating the yamls by hand as described in the doc: https://mlir.llvm.org/docs/Dialects/Linalg/OpDSL/#basic-usage.

**Comment by kurapov-peter** [comment]
Hah, apparently this is just a weird build issue: https://discourse.llvm.org/t/crash-when-running-update-core-linalg-named-ops-sh/66115/3/.
