### ISSUE TITLE
[UT][BUG] UT ExecutionEngine.JitWrapper faild

### ISSUE THREAD

**Issue by huanghaixin008** [intel/graph-compiler#241]
As titled, the ut failed on latest main branch @ commit 8f90cac8e4f4d55b2213767d92f2b0de027ed8e4 [#180](https://github.com/intel/graph-compiler/pull/180)
It seems to be good @ commit 6ba93100c297ec416f3d7fa189bebc9c439b1f8f [#217](https://github.com/intel/graph-compiler/pull/217)
![image](https://github.com/user-attachments/assets/693f5af0-f7aa-47d5-93b2-755308dc95c0)

**Comment by ciyongch** [comment]
How can this kind of failure escape from CI/CD?

**Comment by crazydemo** [comment]
> How can this kind of failure escape from CI/CD?

It seems `gc-check` does not invoke `unittests`, after [PR#126](https://github.com/intel/graph-compiler/pull/126/files)

**Comment by ZhennanQin** [comment]
> > How can this kind of failure escape from CI/CD?
> 
> It seems `gc-check` does not invoke `unittests`, after [PR#126](https://github.com/intel/graph-compiler/pull/126/files)

Would you please enable UT back?

**Comment by crazydemo** [comment]
> > > How can this kind of failure escape from CI/CD?
> > 
> > 
> > It seems `gc-check` does not invoke `unittests`, after [PR#126](https://github.com/intel/graph-compiler/pull/126/files)
> 
> Would you please enable UT back?

@Menooker has an PR to fix it.
