### ISSUE TITLE
Enhance llvm-build behavior 

### ISSUE THREAD

**Issue by WangJialei-A** [intel/graph-compiler#250]
Developers may synchronize the main branch with the PR branch by merging the main branch into the PR branch. This process might generate a commit that includes modifications to the `llvm-version.txt` file, which in turn could trigger the LLVM build CI. 

Perhaps a better approach would be to hook the `llvm-version.txt` file only on the main branch.

**Comment by leshikus** [comment]
There is a problem regarding it, the developer wants their branch to work. If they changed the hash, llvm build has to be made to enable their branch to work.
There is a problem though. The developer has to restart CI on his branch manually once llvm build is completed

**Comment by WangJialei-A** [comment]
> There is a problem regarding it, the developer wants their branch to work. If they changed the hash, llvm build has to be made to enable their branch to work. There is a problem though. The developer has to restart CI on his branch manually once llvm build is completed

I think a better practice is to use a separate PR for updating the LLVM version, rather than mixing it with other development work.

If someone updates the LLVM version on the main branch, I believe it is completely acceptable for the CI results of a PR to fail. This failure serves as a reminder to developers that the LLVM version used in their PR is outdated.

**Comment by leshikus** [comment]
@WangJialei-A I agree

**Comment by leshikus** [comment]
@WangJialei-A do we have something to code here?
