### ISSUE TITLE
`vector.shape_cast` not properly lowered to LLVM

### ISSUE THREAD

**Issue by yifeizh2** [intel/graph-compiler#251]
If a workload involves `tensor.expand_shape` and vector passes at the same time, the final lowered llvm IR contains `unrealized_conversion_cast` op, which cannot be interpreted.

One of the minimum reproducible case is as follows.

```
module {
  func.func @main_entry(%arg0: tensor<2x32x16xf32>, %arg1: tensor<32x16xf32>) -> tensor<32x16xf32> attributes {llvm.emit_c_interface} {
    %expanded_1 = tensor.expand_shape %arg1 [[0, 1], [2]] output_shape [2, 16, 16] : tensor<32x16xf32> into tensor<2x16x16xf32>
    %1 = tensor.empty() : tensor<32x16xf32>
    %6 = linalg.batch_reduce_matmul ins(%arg0, %expanded_1 : tensor<2x32x16xf32>, tensor<2x16x16xf32>) outs(%1 : tensor<32x16xf32>) -> tensor<32x16xf32>
    return %6 : tensor<32x16xf32>
  }
}
```

**Comment by zhczhong** [comment]
Is it because we don't contain `-convert-vector-to-llvm` in our pipeline?

**Comment by yifeizh2** [comment]
> Is it because we don't contain `-convert-vector-to-llvm` in our pipeline?

Partially, adding `-convert-vector-to-llvm` can resolve the issue under a certain cases. We also have other issues.

**Comment by yifeizh2** [comment]
> > Is it because we don't contain `-convert-vector-to-llvm` in our pipeline?
> 
> Partially, adding `-convert-vector-to-llvm` can resolve the issue under a certain cases. We also have other issues.

`-convert-vector-to-llvm` can resolve `unrealized_conversion_cast`, but it also causes explosion in the number of IRs. The compile time is too long to be bearable after the number of MLP layers >=2

**Comment by yifeizh2** [comment]
We can run simple plain-in-plain-out MLP by adding the following 2 passes
```
pm.addPass(createConvertVectorToSCFPass());
pm.addPass(createConvertVectorToLLVMPass());
```

However, the compilation time is too long:
```
{
    "args": {
        "type": "bench",
        "driver": "mlp",
        "batch_size": 128,
        "hidden_size_list": "512x256x128",
        "has_bias": "256x128",
        "act_type": "relu",
        "dtype": "f32",
        "bench_kind": "py",
        "print_ir": false,
        "disable_results_to_params": false,
        "warm_up": 100,
        "repeat": 100
    },
    "compile_cost(ms)": 147815.80170989037,
    "execute_cost(ms)": 0.25182072073221207
}
```

**Comment by BRUCE11111** [comment]
Let me explain something. The vector lower pass is in this [PR #252](https://github.com/intel/graph-compiler/pull/252). 

At the same time, it is best not to use this pass alone if the tiling tensor is large, because the mlir default lower pipeline of vector operation is to full unroll all instructions, resulting in a very long IR. Of course the final result is that the compilation will take a long time and compiled binary file is huge.

Therefore, this pass is usually used with the physical register pass. We will use a for loop to handle the full unroll instructions.
