### ISSUE TITLE
Generate partitions for llama2 and add them to enabling testing

### ISSUE THREAD

**Issue by kurapov-peter** [intel/graph-compiler#26]
Use as a proxy for functionality prioritization.

+goal is to have a set of input jsons that we'll need to be able to compile

> We want to have JSON + actual data for each partition (jsons only describe logical tensors).
>  
> The "automation" means that we want a script, that would generate this pair of a JSON + physical data for each partition and dump it to the disk.
>  
>  dumped jsons = done (please also verify, that the shapes of logical tensors are valid there). Now you need to dump input physical tensors for each partition. You can do so by hooking into the partition::execute method and simply dumping its input physical tensors to the disk as well.
> 
> The goal is to use this pair of 'json + data' later for graph compiler's testing by calling dnnl_graph_compiler_compile(json_part_i, ...) and then dnnl_graph_compiler_execute(data_part_i, ...)

**Comment by lmontigny** [comment]
Details:

- Need all llama2 partitions as json
- To be integrated to onednn backend
- Create script for automation

**Comment by lmontigny** [comment]
_DNNL_ENABLE_GRAPH_DUMP_ 

env. variable defined here:
https://github.com/oneapi-src/oneDNN/blob/87963aae6733a5e5198f859532dbbf1d88dc5a20/src/graph/interface/partition.cpp#L582-L603

**Comment by ciyongch** [comment]
`DNNL_ENABLE_GRAPH_DUMP` will dump all the partitions that oneDNN Graph supports (all backends, like `dnnl` or `gc`), do we have any target(defined) partitions for the future testing? Like `MLP` (and the detail topo) etc?

**Comment by kurapov-peter** [comment]
> `DNNL_ENABLE_GRAPH_DUMP` will dump all the partitions that oneDNN Graph supports (all backends, like `dnnl` or `gc`), do we have any target(defined) partitions for the future testing? Like `MLP` (and the detail topo) etc?

The goal is to get those.
