### ISSUE TITLE
memref-merge optimization

### ISSUE THREAD

**Issue by ciyongch** [intel/graph-compiler#269]
1. A new pass is required to reduce the total memory footprint and improve the cache locality.
2. The static memory planner is required to get the total memory size and the map to each tensor during the compilation stage.
3. The pass is extensible to support different event based ticker and planner.

**Comment by Menooker** [comment]
Is it a dup of https://github.com/intel/graph-compiler/issues/243 ?

**Comment by ciyongch** [comment]
> Is it a dup of #243 ?

Yeah, I didn't notice this issue in the dashboard. Closing this as duplicated.
