### ISSUE TITLE
Create initial performance dashboard

### ISSUE THREAD

**Issue by lmontigny** [intel/graph-compiler#273]
Create the performance dashboard that will track CPU and GPU performance for kernel and ML models.

- [ ] Create dashboard
- [ ] Get info from developers

**Comment by leshikus** [comment]
@ZhennanQin please add requirements for performance dashboard to this bug including what cpu should I use, instructions for measurements, etc

**Comment by lmontigny** [comment]
Idea is to use initially the csv results available on #322 for our Grafana dashboard

**Comment by leshikus** [comment]
The dashboard is created. Comparisons are not yet available, may be added later on request
