### ISSUE TITLE
Create a new backend for onednn with a loader for the compiler

### ISSUE THREAD

**Issue by kurapov-peter** [intel/graph-compiler#3]

**Comment by dchigarev** [comment]
PR: https://github.com/intel-ai/oneDNN/pull/2

**Comment by kurapov-peter** [comment]
@dchigarev, should we close this one?

**Comment by dchigarev** [comment]
> @dchigarev, should we close this one?

@kurapov-peter 

the only thing that's missing in the new backend is this PR https://github.com/kurapov-peter/oneDNN/pull/4 , lets merge it and then we can close this issue

**Comment by dchigarev** [comment]
All PRs from [the list](https://github.com/intel/graph-compiler/issues/3#issuecomment-2092574331) were merged, so closing
