### ISSUE TITLE
`CPUPhysicalRegister` pass failed on SPR with bf16 MLP workload

### ISSUE THREAD

**Issue by yifeizh2** [intel/graph-compiler#313]
The issue currently only reproducible on SPR with the following workload:
```
numactl -C 0-55 -m 0 python3 ./tools/main.py --driver=mlp --batch_size=128 --hidden_size_list=1024x512 --has_bias=512 --act_type=relu --dtype=bf16
```

The LLVM commit used is `a195e2d461dde7c73c6dd24da097affb1a7b6f78`, graph compiler branch is `yifei/mlp_benching_new`.

**Comment by yifeizh2** [comment]
Synced with @BRUCE11111, noticeably, this issue is not reproducible on EMR, and the IR before `CPUPhysicalRegister` pass are identical.

**Comment by BRUCE11111** [comment]
Have fixed on test branch yifei/mlp_benching_new.
