### ISSUE TITLE
Install clang in our runner image

### ISSUE THREAD

**Issue by WangJialei-A** [intel/graph-compiler#319]
Currently `clang/clang++` is not installed in our `self-hosted` runner.
Please help to rebuild the image and redeploy the runner.

https://github.com/intel/graph-compiler/blob/23269d7882419924ff1f4290e2668468ba1525db/.github/dockerfiles/runner/Dockerfile#L12-L17

**Comment by leshikus** [comment]
Ok, will do

**Comment by AndreyPavlenko** [comment]
What about moving the build to clang? It seems a bit faster.

**Comment by leshikus** [comment]
Rebuilt runners with clang, testing it here https://github.com/intel/graph-compiler/actions/runs/10743821428

**Comment by leshikus** [comment]
I have also unified pvc and cpu runner images, the only difference now is in `/dev/dri/renderD128` access

**Comment by lmontigny** [comment]
for nightly test
