### ISSUE TITLE
Correctness check for single op

### ISSUE THREAD

**Issue by ZhennanQin** [intel/graph-compiler#58]
- Cover opset in oneDNN graph.
- Use numpy or pytorch as reference.
- Implement similar data filing as oneDNN.
- Set same numerical tolerance as oneDNN.

**Comment by WangJialei-A** [comment]
@ZhennanQin 
This issue depends on python binding. Please help add #57 into the llama2 milestone too.

**Comment by lmontigny** [comment]
no for CI. capture more bugs from this issue
