### ISSUE TITLE
Action clang-tidy is running in a different environment than build

### ISSUE THREAD

**Issue by AndreyPavlenko** [intel/graph-compiler#93]
It results in the cmake error "OpenMP library could not be found" : https://github.com/intel/graph-compiler/actions/runs/9152095188/job/25159048309#step:10:565

There is also a difference in the cmake command:
https://github.com/intel/graph-compiler/blob/main/.github/workflows/clang-tidy.yml#L75
https://github.com/intel/graph-compiler/blob/main/scripts/compile.sh#L24

I think, it would be reasonable to move clang-tidy into the build script. In this case, it will be running in the same env and reusing the build artifacts, that will make the CI checks a bit faster.

**Comment by WangJialei-A** [comment]
Hi @AndreyPavlenko @ZhennanQin 
`clang-tidy` requires `clang` compiler. 
Using `clang-tidy` and `gcc` together may result in compatibility issues (see [here](https://stackoverflow.com/questions/57082124/how-to-integrate-clang-tidy-to-cmake-and-gcc)). 
So we cannot leverage the compile script or reuse the build artifacts.

For `OpenMP` issue, we need to check whether `libomp-dev` and some related pakages are installed or not in the running image.

**Comment by WangJialei-A** [comment]
Hi, @AndreyPavlenko 
#94 fixed the OpenMP problem. Please reopen this issue if you still have concerns on the `cmake` configuration.
